tusc_api:
  tusc_wallet_port: "8091"
  tusc_wallet_ip: "localhost"
  tusc_wallet_rpc_endpoint: "/rpc"
  tusc_wallet_rpc_version: "2.0"
  swap_account_name: "occtotusc"
db:
  host: "localhost"
  user: "postgres"
  password: "fakepass"
  database: "tusc-swap"
  port: 5432
eth_api:
  apikey: "UNKNOWN"
  ethereum_network_api_url: "https://api.etherscan.io/api"
  wallet_address_occ_omega: "UNKNOWN"
  occ_contract_address: "0x75584b2bfa5eb391c8234abcfb4cde5c07e2cf30"
general:
  shut_off_date: "2019-6-13 11:11:00"  # In UTC timezone
  testing: False
  swap_interval: 900 # in seconds.
